# Generated by Django 3.2.20 on 2023-07-20 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
